[package]
name = "tailor-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tailor"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
reqwest = { version = "0.12.20", features = ["blocking"] }
serde = "1.0.219"
sha2 = "0.10.9"
toml = "0.8.23"
