[package]
name = "zephyr"
version = "3.5.0"
edition = "2025"
type = "sdk"
src = []
include = []

[[feature]]
name = ""
src = []
include = []

[commands]
build = "west build -p -b $board"
run = "west flash"
clean = "rm -rf build"
debug = "west debug"
